### ISSUE TITLE
Add a wiki of useful commands and how to use the mod

### ISSUE THREAD

**Issue by AstroOrbis** [pleasegivesource/SalHackSkid#15]
**Is your feature request related to a problem? Please describe.**

Use github’s wiki feature to make a wiki

**Describe the solution you'd like**

Create a wiki

**Describe alternatives you've considered**

Just figure it out

**Additional context**

**Comment by ElliotOnTop** [comment]
i hate you

**Comment by AstroOrbis** [comment]
?

**Comment by liu7d7** [comment]
no
